import React, { useEffect, useState } from 'react';
import { Link } from "wouter";
import { motion } from 'framer-motion';
import { Card, CardContent, CardFooter, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Navigation, Footer } from '@/components/layout';
import { WaveSection } from '@/components/ui/wave-section';
import { Calendar, User, ArrowRight, Loader2 } from 'lucide-react';
// import { SeobotClient } from 'seobot'; // Uncomment when API key is available

// Mock data for display purposes
const MOCK_ARTICLES = [
  {
    id: '1',
    slug: '5-reasons-your-business-needs-a-website',
    title: '5 Reasons Your Service Business Needs a Professional Website in 2025',
    excerpt: 'In today’s digital age, relying solely on word-of-mouth isn’t enough. Discover why a professional website is crucial for growth.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    date: 'Oct 12, 2025',
    author: 'Tyler Huff',
    category: 'Business Growth'
  },
  {
    id: '2',
    slug: 'seo-basics-for-contractors',
    title: 'SEO Basics: How to Get Your Construction Business Found on Google',
    excerpt: 'Stop losing leads to competitors. Learn the fundamental SEO strategies that will put your business on the map.',
    image: 'https://images.unsplash.com/photo-1557838402-21d133044992?auto=format&fit=crop&q=80&w=800',
    date: 'Oct 05, 2025',
    author: 'Tyler Huff',
    category: 'Marketing'
  },
  {
    id: '3',
    slug: 'maximize-google-business-profile',
    title: 'How to Maximize Your Google Business Profile for More Calls',
    excerpt: 'Your Google Business Profile is often the first thing customers see. Make sure it’s working hard for you.',
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800',
    date: 'Sep 28, 2025',
    author: 'Tyler Huff',
    category: 'Local SEO'
  }
];

export default function BlogPage() {
  const [articles, setArticles] = useState(MOCK_ARTICLES);
  const [loading, setLoading] = useState(false);

  /* 
   * SEObot Integration Example
   * 
   * Once you have your API key from app.seobotai.com, you can uncomment this code
   * to fetch real articles generated by the AI.
   */
  
  /*
  useEffect(() => {
    async function fetchArticles() {
      try {
        setLoading(true);
        // const client = new SeobotClient("YOUR_API_KEY");
        // const data = await client.getArticles({ page: 1, limit: 10 });
        // setArticles(data);
      } catch (error) {
        console.error("Failed to fetch articles:", error);
      } finally {
        setLoading(false);
      }
    }
    
    // fetchArticles();
  }, []);
  */

  return (
    <div className="min-h-screen bg-[#fdfaf5] text-gray-800 font-sans">
      <Navigation />

      <WaveSection 
        className="pt-32 md:pt-40 pb-48" 
        disableTopWave
        backgroundImage="https://staging44.twentyonesolutions.com/wp-content/uploads/2025/12/gab6baae1b7715596462e080861b1563705c06e9bf501a606e520de746ba7f2488c7fc78479ca513f726e1153f5fb4005_1280-360965.webp"
        overlayOpacity={0.75}
      >
        <div className="container mx-auto px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1 className="text-4xl md:text-6xl font-bold font-heading text-gray-900 mb-6 leading-tight">
              Latest Insights
            </h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
              Tips, strategies, and guides to help your service business grow online.
            </p>
          </motion.div>
        </div>
      </WaveSection>

      <section className="py-12 pb-24">
        <div className="container mx-auto px-6">
          {loading ? (
            <div className="flex justify-center py-20">
              <Loader2 className="w-10 h-10 animate-spin text-[#FD9800]" />
            </div>
          ) : (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {articles.map((article, index) => (
                <motion.div
                  key={article.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <Link href={`/blog/${article.slug}`}>
                    <Card className="h-full border-0 shadow-lg hover:shadow-xl transition-all hover:-translate-y-1 cursor-pointer bg-white overflow-hidden group">
                      <div className="h-48 overflow-hidden relative">
                         <div className="absolute top-4 left-4 bg-[#FD9800] text-white text-xs font-bold px-3 py-1 rounded-full z-10">
                            {article.category}
                         </div>
                         <img 
                           src={article.image} 
                           alt={article.title} 
                           className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                         />
                      </div>
                      <CardHeader className="pb-2">
                        <div className="flex items-center gap-4 text-xs text-gray-500 mb-2">
                          <div className="flex items-center gap-1">
                            <Calendar className="w-3 h-3" />
                            {article.date}
                          </div>
                          <div className="flex items-center gap-1">
                            <User className="w-3 h-3" />
                            {article.author}
                          </div>
                        </div>
                        <h3 className="text-xl font-bold font-heading text-gray-900 leading-tight group-hover:text-[#FD9800] transition-colors">
                          {article.title}
                        </h3>
                      </CardHeader>
                      <CardContent>
                        <p className="text-gray-600 text-sm line-clamp-3">
                          {article.excerpt}
                        </p>
                      </CardContent>
                      <CardFooter className="pt-0">
                        <span className="text-[#FD9800] font-semibold text-sm flex items-center gap-1 group-hover:gap-2 transition-all">
                          Read Article <ArrowRight className="w-4 h-4" />
                        </span>
                      </CardFooter>
                    </Card>
                  </Link>
                </motion.div>
              ))}
            </div>
          )}
          
          <div className="mt-16 text-center">
             <div className="inline-block p-4 bg-blue-50 border border-blue-100 rounded-lg text-left max-w-2xl">
                <h4 className="font-bold text-blue-900 mb-2 flex items-center gap-2">
                   <span className="bg-blue-600 text-white text-xs px-2 py-0.5 rounded">DEV NOTE</span>
                   SEObot Integration Ready
                </h4>
                <p className="text-sm text-blue-800">
                   The <code>seobot</code> package is installed. To enable auto-blogging:
                   <ol className="list-decimal ml-4 mt-2 space-y-1">
                      <li>Get your API Key from <strong>app.seobotai.com</strong></li>
                      <li>Uncomment the integration code in <code>client/src/pages/blog.tsx</code></li>
                      <li>Your AI-generated articles will automatically appear here!</li>
                   </ol>
                </p>
             </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
